- name: install nginx
  hosts: all

  tasks:
  - name: install nginx
    yum: name=htp state=lates

  - name: Copy my page to server
    copy: src={{source_file}} dest={{destin_file}} mode=0555
    notify: Restart  Nginx

