- name: Create MinIO Bucket
  hosts: localhost
  tasks:
    - name: Ensure MinIO bucket exists
      community.general.minio_bucket:
        endpoint: http://your-minio-server:9000
        access_key: your-access-key
        secret_key: your-secret-key
        bucket_name: your-bucket-name
        state: present
      register: minio_bucket_result

    - name: Display result
      debug:
        var: minio_bucket_result
