
---
    name: install packages
    hosts: all
    vars:
        packages:
            - name: nginx
              required: true
            - name: postgresql
              required: true
            - name: httpd
              required: false
    tasks:
        - name: install "{{ item.name }}" on Ubuntu
          apt:
              name: "{{item.name}}"
              state: present
          loop: "{{ packages }}"
